name: "Build packages"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: build
      cancel-in-progress: true

    strategy:
      matrix:
        node-version: [22.5.1]

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.21

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build
